### ISSUE TITLE
Error 403 for the generated token

### ISSUE THREAD

**Issue by mfuxi** [ncorrare/vault-java-example#1]
Getting:
```
Error reading secret/<someSecret>: Error making API request.

URL: GET http://<vaultURL>:8200/v1/secret/<someSecret>
Code: 403. Errors:

* permission denied
```
I'm getting this error when i'm running the commands manually as well not only from Jenkins and then try to read the secret with the generated token.. only when I use the root token it manages to read the secret.

What am I missing here?

**Comment by saikirandusari** [comment]
@mfuxi  How did you resolve this problem? I am having the same problem.

Thanks
Sai
